# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privatemessages', '0003_thread_deal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=500)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privatemessages.Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
