# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0027_auto_20180205_1752'),
        ('privatemessages', '0004_dealrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrole',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offers.Wallet'),
        ),
    ]
