# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('pay', models.CharField(default='', max_length=100)),
                ('get', models.CharField(default='', max_length=100)),
                ('reserve', models.CharField(default='', max_length=100)),
                ('mode', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CEther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('pay', models.CharField(default='', max_length=100)),
                ('get', models.CharField(default='', max_length=100)),
                ('reserve', models.CharField(default='', max_length=100)),
                ('mode', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CLite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('pay', models.CharField(default='', max_length=100)),
                ('get', models.CharField(default='', max_length=100)),
                ('reserve', models.CharField(default='', max_length=100)),
                ('mode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
