# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_cbit_cether_clite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbit',
            name='get',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbit',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbit',
            name='mode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbit',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbit',
            name='pay',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cbit',
            name='reserve',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='get',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='mode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='pay',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cether',
            name='reserve',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='get',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='mode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='pay',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clite',
            name='reserve',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='futureuser',
            name='email',
            field=models.EmailField(help_text='Введите ящик для подписки на наши уведомления', max_length=30),
        ),
    ]
