# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20171005_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureuser',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
