# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_auto_20171005_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Введите адрес ящика для подписки.'}, max_length=30, validators=[django.core.validators.EmailValidator]),
        ),
    ]
