# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20170912_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Open', max_length=30),
        ),
    ]
