# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_auto_20170912_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Sent', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.CharField(max_length=30, null=True)),
                ('information', models.CharField(max_length=30, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
