# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20170914_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='demand_type',
            field=models.CharField(max_length=30, null=True, verbose_name='Что хочу получить/предложить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('1 BTC', '1 BTC'), ('1 LTC', '1 LTC'), ('1 ETH', '1 ETH')], default='1 BTC', max_length=30, null=True, verbose_name='Что продаю'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sellorbuy',
            field=models.CharField(choices=[('ПРОДАЖА', 'ПРОДАЖА'), ('ПОКУПКА', 'ПОКУПКА')], default='ПРОДАЖА', max_length=30, null=True, verbose_name='Продать/купить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Open', max_length=30, verbose_name='Статус'),
        ),
    ]
