# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0009_auto_20171013_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Open', max_length=30, verbose_name='Статус')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('buy', models.CharField(default=0, max_length=200)),
                ('sale', models.CharField(default=0, max_length=200)),
                ('replies_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Sent', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.CharField(max_length=30, null=True, verbose_name='Количество продажи')),
                ('proffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Proffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.CharField(max_length=30, null=True, verbose_name='Предлагаемая цена покупки/продажи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('1 BTC', '1 BTC'), ('1 LTC', '1 LTC'), ('1 ETH', '1 ETH'), ('1 DASH', '1 DASH'), ('1 ZEC', '1 ZEC'), ('1 XMR', '1 XMR')], default='1 BTC', max_length=30, null=True, verbose_name='Что продаю/покупаю'),
        ),
    ]
