# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_proffer_type_of_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='sellorbuy',
            field=models.CharField(choices=[('ПРОДАЖА', 'ПРОДАЖА'), ('ПОКУПКА', 'ПОКУПКА')], default='ПРОДАЖА', max_length=30, null=True, verbose_name='Продать/купить'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='quantity',
            field=models.CharField(max_length=30, null=True, verbose_name='Количество'),
        ),
    ]
