# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20171017_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Альфабанк', 'Альфабанк'), ('Тинькофф-банк', 'Тинькофф-банк')], default='Сбербанк', max_length=30, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=30, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('ZEC', 'ZEC'), ('XMR', 'XMR')], default='BTC', max_length=30, null=True, verbose_name='Что продаю/покупаю'),
        ),
    ]
