# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20171030_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Draft', max_length=30),
        ),
        migrations.AddField(
            model_name='proffer',
            name='state',
            field=models.CharField(default='Draft', max_length=30),
        ),
    ]
