# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20171124_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursecourse',
            name='type',
        ),
    ]
