# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_remove_bursecourse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='burse',
            field=models.CharField(choices=[('Bittrex', 'Bittrex'), ('Bitfinex', 'Bitfinex'), ('Poloniex', 'Poloniex'), ('Kraken', 'Kraken')], max_length=30, verbose_name='Биржа'),
        ),
    ]
