# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0020_auto_20171128_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(max_length=100, verbose_name='Секретный ключ')),
                ('public_key', models.CharField(max_length=100, verbose_name='Публичный ключ')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес кошелька Bitcoin')),
                ('balance', models.CharField(default='0', max_length=100, verbose_name='Баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
