# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_auto_20171206_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiat',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма в фиатной валюте'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('DASH', 'DASH'), ('ZEC', 'ZEC'), ('XMR', 'XMR'), ('BTC', 'BTC'), ('LTC', 'LTC'), ('ETH', 'ETH')], default='BTC', max_length=30, null=True, verbose_name='Что продаю/покупаю'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default='0.00000000', max_length=300, verbose_name='Баланс'),
        ),
    ]
