# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_auto_20171213_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(default='User', max_length=30, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='owner',
            field=models.CharField(default='User', max_length=30, verbose_name='Владелец'),
        ),
    ]
