# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_auto_20171213_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
