# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_wallet_ethaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='btcaddress',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='btcbalance',
            field=models.CharField(default='0.00000000', max_length=300, verbose_name='Баланс BTC'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ethbalance',
            field=models.CharField(default='0.00000000', max_length=300, verbose_name='Баланс ETH'),
        ),
    ]
