# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0028_dealrole_tempwallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proffer',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='proffer',
            name='sale',
        ),
        migrations.AddField(
            model_name='proffer',
            name='rate',
            field=models.CharField(default=0, max_length=200, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='type',
            field=models.CharField(choices=[('КУПЛЮ', 'ПРОДАМ')], default='КУПЛЮ', max_length=30, verbose_name='Тип'),
        ),
    ]
