# Generated by Django 2.1.1 on 2018-12-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_auto_20180914_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_banks', models.IntegerField(default=1)),
                ('bank_a', models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Банк')),
                ('bank_b', models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Банк')),
                ('bank_c', models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Банк')),
                ('bank_d', models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Банк')),
                ('bank_e', models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Банк')),
            ],
        ),
        migrations.AlterField(
            model_name='proffer',
            name='bank',
            field=models.CharField(default='Сбербанк', max_length=30, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='banks',
            name='proffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Proffer'),
        ),
    ]
