# Generated by Django 2.1.1 on 2018-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0031_auto_20181203_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='proffer',
        ),
        migrations.AddField(
            model_name='proffer',
            name='bank_promsvyaz',
            field=models.BooleanField(default=False, verbose_name='Промсвязьбанк'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='bank_qiwi',
            field=models.BooleanField(default=False, verbose_name='Qiwi'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='bank_sber',
            field=models.BooleanField(default=True, verbose_name='Сбербанк'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='bank_tinkoff',
            field=models.BooleanField(default=False, verbose_name='Тинькофф'),
        ),
        migrations.AddField(
            model_name='proffer',
            name='bank_vtb',
            field=models.BooleanField(default=False, verbose_name='Втб-24'),
        ),
        migrations.DeleteModel(
            name='Banks',
        ),
    ]
