# Generated by Django 2.1.1 on 2018-12-12 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0032_auto_20181204_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sellorbuy',
            field=models.CharField(choices=[('ПРОДАЖА', 'ПРОДАЖА'), ('ПОКУПКА', 'ПОКУПКА')], default='ПРОДАЖА', max_length=30, null=True, verbose_name='Продать/купить'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proffer',
            name='bank',
            field=models.CharField(default='Сбербанк', max_length=200, verbose_name='Банк'),
        ),
    ]
