# Generated by Django 2.1.1 on 2018-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0033_auto_20181212_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffer',
            name='bank_search',
            field=models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк')], default='Сбербанк', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
