# Generated by Django 2.1.1 on 2019-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0036_auto_20190212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffer',
            name='bank_alfa',
            field=models.BooleanField(default=False, verbose_name='Альфабанк'),
        ),
    ]
