# Generated by Django 2.1.1 on 2019-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0037_proffer_bank_alfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffer',
            name='bank_search',
            field=models.CharField(choices=[('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Втб-24', 'Втб-24'), ('Промсвязьбанк', 'Промсвязьбанк'), ('Альфабанк', 'Альфабанк'), ('Qiwi', 'Qiwi')], default='Сбербанк', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
