# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_post', models.BooleanField(default=True, verbose_name='После размещения ордера')),
                ('offer_post', models.BooleanField(default=True, verbose_name='После размещения предложения')),
                ('order_reply', models.BooleanField(default=True, verbose_name='После ответа на ордер')),
                ('offer_reply', models.BooleanField(default=True, verbose_name='После ответа на предложение')),
                ('after_deal', models.BooleanField(default=True, verbose_name='После сделки')),
                ('support', models.BooleanField(default=True, verbose_name='Уведомления поддержки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
