# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alreadyenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='alreadyenter',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
