# Generated by Django 2.1.1 on 2018-09-14 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alreadyenter_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='offer_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='after_deal',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='offer_reply',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='order_post',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='order_reply',
        ),
        migrations.AddField(
            model_name='notifications',
            name='chat',
            field=models.BooleanField(default=True, verbose_name='После начала чата'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='deal',
            field=models.BooleanField(default=True, verbose_name='После начала сделки'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='reply',
            field=models.BooleanField(default=True, verbose_name='После ответа на ваше предложение'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
