# Generated by Django 2.1.1 on 2019-01-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180914_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(null=True, unique=True, verbose_name='Процент от сделки')),
                ('address', models.CharField(default='', max_length=200, unique=True, verbose_name='Адрес единственного кошелька для отчислений')),
                ('sum', models.FloatField(null=True, unique=True, verbose_name='Сумма всех сделок')),
                ('walletsum', models.FloatField(null=True, unique=True, verbose_name='Сумма на кошельке в данный момент')),
                ('count', models.FloatField(null=True, unique=True, verbose_name='Количество всех сделок')),
            ],
        ),
    ]
