# Generated by Django 2.1.1 on 2019-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес единственного кошелька для отчислений'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='count',
            field=models.FloatField(null=True, verbose_name='Количество всех сделок'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='percent',
            field=models.FloatField(null=True, verbose_name='Процент от сделки'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='sum',
            field=models.FloatField(null=True, verbose_name='Сумма всех сделок'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='walletsum',
            field=models.FloatField(null=True, verbose_name='Сумма на кошельке в данный момент'),
        ),
    ]
